services:

  qdrant:
    image: qdrant/qdrant:v1.13.5
    restart: unless-stopped
    container_name: qdrant
    volumes:
      - ./qdrant_data:/qdrant/storage
    # TODO: Remove this in production
    ports:
      - 6333:6333